export const imoveisExemplo = [
  {
    id: 1,
    titulo: "Apartamento Moderno no Centro",
    tipo: "Apartamento",
    transacao: "Venda",
    preco: "550000",
    endereco: "Rua das Flores, 123, Centro",
    quartos: 2,
    banheiros: 2,
    vagas: 1,
    area: 75,
    descricao:
      "Apartamento recém-reformado com acabamentos de alta qualidade. Perto de tudo.",
    condominio: "450",
    iptu: "1200",
    mobiliado: true,
    piscina: false,
    churrasqueira: true,
    imagem: "https://picsum.photos/seed/imovel1/600/400",
    imageHint: "modern apartment",
    status: "Disponível",
    dataInicioOcupacao: undefined,
    dataFimOcupacao: undefined,
  },
  {
    id: 2,
    titulo: "Casa Espaçosa com Quintal",
    tipo: "Casa",
    transacao: "Aluguel",
    preco: "3500",
    endereco: "Avenida das Árvores, 456, Bairro Jardim",
    quartos: 3,
    banheiros: 3,
    vagas: 2,
    area: 180,
    descricao:
      "Casa ampla com quintal grande, perfeita para famílias. Área de lazer com churrasqueira.",
    condominio: "0",
    iptu: "2500",
    mobiliado: false,
    piscina: true,
    churrasqueira: true,
    imagem: "https://picsum.photos/seed/imovel2/600/400",
    imageHint: "spacious house",
    status: "Alugado",
    dataInicioOcupacao: "2024-01-10",
    dataFimOcupacao: "2025-01-10",
  },
  {
    id: 3,
    titulo: "Kitnet Aconchegante Próxima à Universidade",
    tipo: "Kitnet",
    transacao: "Venda",
    preco: "250000",
    endereco: "Rua dos Estudantes, 789, Bairro Universitário",
    quartos: 1,
    banheiros: 1,
    vagas: 0,
    area: 35,
    descricao:
      "Kitnet funcional e bem localizada, ideal para estudantes. Totalmente mobiliada.",
    condominio: "150",
    iptu: "500",
    mobiliado: true,
    piscina: false,
    churrasqueira: false,
    imagem: "https://picsum.photos/seed/imovel3/600/400",
    imageHint: "cozy studio",
    status: "Disponível",
    dataInicioOcupacao: undefined,
    dataFimOcupacao: undefined,
  },
  {
    id: 4,
    titulo: "Terreno Amplo em Condomínio Fechado",
    tipo: "Terreno",
    transacao: "Venda",
    preco: "450000",
    endereco: "Condomínio Vale Verde, Lote 12",
    quartos: 0,
    banheiros: 0,
    vagas: 0,
    area: 1000,
    descricao:
      "Terreno plano e pronto para construir em condomínio com segurança 24h e área de lazer.",
    condominio: "300",
    iptu: "1800",
    mobiliado: false,
    piscina: false,
    churrasqueira: false,
    imagem: "https://picsum.photos/seed/imovel4/600/400",
    imageHint: "empty lot",
    status: "Reservado",
    dataInicioOcupacao: "2024-08-01",
    dataFimOcupacao: "2024-08-15",
  },
  {
    id: 5,
    titulo: "Apartamento Duplex com Vista Panorâmica",
    tipo: "Apartamento",
    transacao: "Venda",
    preco: "1200000",
    endereco: "Avenida Principal, 101, Cobertura",
    quartos: 4,
    banheiros: 4,
    vagas: 3,
    area: 220,
    descricao:
      "Cobertura duplex de alto padrão, com piscina privativa e vista deslumbrante da cidade.",
    condominio: "1800",
    iptu: "8000",
    mobiliado: true,
    piscina: true,
    churrasqueira: true,
    imagem: "https://picsum.photos/seed/imovel5/600/400",
    imageHint: "duplex apartment",
    status: "Em Manutenção",
    dataInicioOcupacao: "2024-07-20",
    dataFimOcupacao: "2024-07-25",
  },
  {
    id: 6,
    titulo: "Casa de Vila Charmosa",
    tipo: "Casa",
    transacao: "Aluguel",
    preco: "2800",
    endereco: "Vila das Orquídeas, Casa 5",
    quartos: 2,
    banheiros: 1,
    vagas: 1,
    area: 90,
    descricao:
      "Casa de vila charmosa e segura, em rua tranquila. Recém-reformada.",
    condominio: "0",
    iptu: "950",
    mobiliado: false,
    piscina: false,
    churrasqueira: false,
    imagem: "https://picsum.photos/seed/imovel6/600/400",
    imageHint: "charming house",
    status: "Disponível",
    dataInicioOcupacao: undefined,
    dataFimOcupacao: undefined,
  },
  {
    id: 7,
    titulo: "Apartamento para Aluguel Temporada",
    tipo: "Apartamento",
    transacao: "Aluguel",
    preco: "4200",
    endereco: "Avenida Beira Mar, 789",
    quartos: 2,
    banheiros: 2,
    vagas: 1,
    area: 85,
    descricao:
      "Apartamento de frente para o mar, ideal para temporada. Totalmente mobiliado.",
    condominio: "600",
    iptu: "1500",
    mobiliado: true,
    piscina: true,
    churrasqueira: true,
    imagem: "https://picsum.photos/seed/imovel7/600/400",
    imageHint: "beachfront apartment",
    status: "Alugado",
    dataInicioOcupacao: "2024-07-01",
    dataFimOcupacao: "2024-07-31",
  },
];
